// Generated by scripts/rekey.py: translated MKW functions the runtime calls that have no WSR
// equivalent. Each aborts loudly if reached, so the build links while the port is incomplete.
#include <cstdio>
#include <cstdlib>
#include "ppc_runtime.h"

extern "C" void func_801D8D30(CpuContext*) {
    std::fprintf(stderr, "[resortcompiled] called unmapped MKW function 0x801D8D30 (NHTTPStartup)\n");
    std::abort();
}

extern "C" void func_801D9E94(CpuContext*) {
    std::fprintf(stderr, "[resortcompiled] called unmapped MKW function 0x801D9E94 (NHTTPi_GetSystemInfoP)\n");
    std::abort();
}

extern "C" void func_8055531C(CpuContext*) {
    std::fprintf(stderr, "[resortcompiled] called unmapped MKW function 0x8055531C (RelProlog)\n");
    std::abort();
}

